-- upgrade --
CREATE TABLE IF NOT EXISTS "group" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "admin" INT NOT NULL
);
CREATE TABLE IF NOT EXISTS "sub" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "type" VARCHAR(10) NOT NULL,
    "type_id" INT NOT NULL,
    "uid" INT NOT NULL,
    "live" INT NOT NULL,
    "dynamic" INT NOT NULL,
    "at" INT NOT NULL,
    "bot_id" INT NOT NULL
);
CREATE TABLE IF NOT EXISTS "user" (
    "uid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS "version" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSON NOT NULL
);
