# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/app/archive/middleware/v1/preload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0bilibili/app/archive/middleware/v1/preload.proto\x12\"bilibili.app.archive.middleware.v1\"J\n\nPlayerArgs\x12\n\n\x02qn\x18\x01 \x01(\x03\x12\r\n\x05\x66nver\x18\x02 \x01(\x03\x12\r\n\x05\x66nval\x18\x03 \x01(\x03\x12\x12\n\nforce_host\x18\x04 \x01(\x03\x62\x06proto3')



_PLAYERARGS = DESCRIPTOR.message_types_by_name['PlayerArgs']
PlayerArgs = _reflection.GeneratedProtocolMessageType('PlayerArgs', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERARGS,
  '__module__' : 'bilibili.app.archive.middleware.v1.preload_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.archive.middleware.v1.PlayerArgs)
  })
_sym_db.RegisterMessage(PlayerArgs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERARGS._serialized_start=88
  _PLAYERARGS._serialized_end=162
# @@protoc_insertion_point(module_scope)
